sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EibZvUC2W5ezbcnkV7GqD8CEw3CzfEYRDZ9i0bQTzNZpDMHfmyUpOpYBQSRGvAumJ4xNnHaeG97zZzCx39uW1ZVDfTWgyP2jyDhPjzig51N5/VzLgnqtc2I/WQ+TowLo3gJI2Yx7UeVcRoCFkaTCsc52TuO411y0rBBkMX0TY6z2nDQpjeXyy1LLx8BYyeROHdyB8ABSon4JneUFLlFTbHoiW0M/XT0jPQkOCdkTEuxCJkq9p+rYET+UQYVMOGRETxEK7VbwC61V8C3KSGEI4vfZjKQtKWEG/xGsRLo93bLSJiprvAcJ1xI5Ylj3VepCFTErJ5r4+QmZAYpNTv3W7WZGgxg+HG8e8Ku4/E9aaLwptt7bLbqG9BL8J7Jwvf+xr6gV3zChKBODyIBrbT4yMrM9+ZbfhWCl45F3WLPQBGqT/xOn0t9aN9iEVJ0In1f/2HcXyoFgLyMEvKDY0EJVawVTZcdfA4TpgRfSHih+HOgn3cNEhtQ33LeqG+U4/qRCrEJI9xdBLlT+QpQ1hwyVMxGfHxAYf/Fpe54wTbVqie2IlNdLpEs8x/eHc1bbYgCUmmQ0XjOCPyCbeK49COiEfLhulwkRM9EDw4X2ZA/qHL9Y+pNEjTA0o3DOPgVT5I/cnGeZES5rRel5wDF7l+wbGkmco+6hOcZ3ecCOUHt4M74=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Fletcher-of-Madeley_6160
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy